[package]
name = "wpdm-common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
